name: I am Alex Dou
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
title: "Alex Dou: Product, Photography, third thing beginning with 'P'"
description: "My name is Alex Dou. I am trying to create a little corner of the Internet for myself to maintain, customize, and live in. Feel free to come in and take a look around, I just ask that you take off your shoes and put on these fuzzy slippers."
plugins:
  - jekyll-seo-tag
url: https://alexanderdou.com
baseurl: /
